### ISSUE TITLE
你好，你这个仓库的代码缺少了这个包的代码：com.misterchan.iconeditor.databinding，应该是没有加入版本控制中

### ISSUE THREAD

**Issue by wenj91** [MISTER-CHAN/icon-editor#1]
rt

**Comment by MISTER-CHAN** [comment]
通过 View Binding 功能，系统会为每个布局在 databinding 包中自动生成绑定类。要启用 View Binding，请确保 `app\build.gradle` 中包含如下代码：
```gradle
android {
    ...
    buildFeatures {
        viewBinding true
    }
}
```
该功能在 Android Studio 3.6 及更高版本中可用

**Comment by MISTER-CHAN** [comment]
通过 View Binding 功能，系统会为每个布局在 databinding 包中自动生成绑定类。要启用 View Binding，请确保 `app\build.gradle` 中包含如下代码：
```gradle
android {
    ...
    buildFeatures {
        viewBinding true
    }
}
```
该功能在 Android Studio 3.6 及更高版本中可用。

**Comment by wenj91** [comment]
> 通过 View Binding 功能，系统会为每个布局在 databinding 包中自动生成绑定类。要启用 View Binding，请确保 `app\build.gradle` 中包含如下代码：
> 
> ```groovy-gradle
> android {
>     ...
>     buildFeatures {
>         viewBinding true
>     }
> }
> ```
> 
> 该功能在 Android Studio 3.6 及更高版本中可用。

了解了，感谢^_^
