### ISSUE TITLE
Color palette slot/selection needs an improvement.

### ISSUE THREAD

**Issue by Arxance** [MISTER-CHAN/icon-editor#3]
Every new colors that are inserted or probably picked it somewhere will only exist in one session, after restarting the app (or android somehow kills it), those colors are pretty much gone and back to default presets. this honestly needs to be fixed since manually picking colors due to that is absolute nightmare.

Also maybe add some additional features like ability to automatically pick all of colors via image/sprite, might probably gonna be alot useful.

**Comment by MISTER-CHAN** [comment]
Another new version has been released and now you can keep your palette colors.

The feature you mentioned at the end won't be planned temporarily. A 32-bit image may contain thousands of different colors. I don't think it's appropriate for the palette to hold so many colors.
If I misunderstood your words, please correct.

**Comment by Arxance** [comment]
Thanks.

Also the feature - you could add an warning dialog about inserting a image that contains many thousands of colors, but this one is pretty much useful in some cases in "Lospec" pixel art color palette website, from that website, you might or have to download the color palette as image, then import them, something like that.

There's alot of room improvement in color palette, like ability to edit colors and delete them, select and create your own color palette "folder" where you can switch the default to your own etc or maybe ability to use aesprite's color palette format. Overall this is pretty great project and looking forward for it to be improved!

**Comment by MISTER-CHAN** [comment]
> like ability to edit colors and delete them,

This feature already exists. By long clicking a color you can edit or delete it. You can even move it to a different position in the palette by dragging it.

**Comment by MISTER-CHAN** [comment]
Now you can add all of the colors from a sprite to the palette by long clicking the `+` button. Enjoy the new feature!

**Comment by Arxance** [comment]
oh, thanks you!
